/*
 * Principal.java
 *
 * Created on 13/05/2014, 22:27
 */
package jadados;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author mello
 */
public class Principal extends javax.swing.JFrame {

    /* Responsável pelo tempo que os dados ficarão saltando (trocando de face) */
    private final Random r1;

    /* Face dos dados que ficou para cima */
    private int faceDado1, faceDado2;

    
    public Principal() {
        initComponents();

        // Fazendo com que a janela da aplicacao fique centralizada ao ser inciada
        this.setLocationRelativeTo(null);

        // Criando o gerador de números pseudo-aleatórios
        r1 = new Random();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLDado1 = new javax.swing.JLabel();
        jLDado2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLTotalLancamentos = new javax.swing.JLabel();
        jBApostar = new javax.swing.JButton();
        jBLancar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        jTFAposta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLBuscado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JaDados - Jogo de Dados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadados/resources/jadados.png"))); // NOI18N

        jLDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadados/resources/jadados.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDado2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDado1)
                    .addComponent(jLDado2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo"));

        jLabel1.setText("Saldo:");

        jLabel2.setText("Total de lançamentos:");

        jLTotalLancamentos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLTotalLancamentos.setText("0");

        jBApostar.setText("Apostar");
        jBApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApostarActionPerformed(evt);
            }
        });

        jBLancar.setText("Lançar dados");
        jBLancar.setEnabled(false);
        jBLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLancarActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor da aposta:");

        jLSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSaldo.setText("100");

        jTFAposta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFAposta.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLTotalLancamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBApostar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jBLancar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSaldo)
                            .addComponent(jTFAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLTotalLancamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBApostar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLancar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Regras"));

        jLabel6.setText("O jogador ganha se a soma for:");

        jLabel7.setText("O jogador perde se a soma for:");

        jLabel8.setText("7 ou 11");

        jLabel9.setText("2, 3 ou 12");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(80, 80, 80))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18))
        );

        jLabel10.setText("Número a ser buscado:");

        jLBuscado.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLBuscado.setText("7 ou 11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLBuscado)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLBuscado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApostarActionPerformed

        /* Ativando e desativando componentes na tela */
        jBLancar.setEnabled(true);
        jBApostar.setEnabled(false);
        jTFAposta.setEnabled(false);
        // mandando o focus para o botao Lancar
        jBLancar.requestFocus();

        JOptionPane.showMessageDialog(this, "Você está apostando " + jTFAposta.getText(), "Atenção", JOptionPane.WARNING_MESSAGE);
        // codigos dos icones
        //JOptionPane.WARNING_MESSAGE; Atencao
        //JOptionPane.ERROR_MESSAGE; Erro
        //JOptionPane.INFORMATION_MESSAGE; Informacao
    }//GEN-LAST:event_jBApostarActionPerformed

    /**
     * Cada dado irá saltar um número aleatório de vezes, então pode ser que um
     * termine de saltar antes do outro. É importante fazer a soma das faces
     * somente após ambos pararem de saltar.
     *
     * Este método está incompleto e precisa ser corrigido.
     */
    public void verificaSoma(int dado1, int dado2) {

        int soma = this.faceDado1 + this.faceDado2;
        
        int saldo = new Integer(jLSaldo.getText());

        if ((soma == 7) || (soma == 11)) {
            JOptionPane.showMessageDialog(this, "Você ganhou!", "Parabéns", JOptionPane.INFORMATION_MESSAGE);

            // obtendo a string do saldo
            //int saldo = new Integer(jLSaldo.getText());

            // obtendo a string da aposta
            int aposta = new Integer(jTFAposta.getText());

            // aumentando o saldo
            saldo += aposta;

            // gravando no jLSaldo
            jLSaldo.setText("" + saldo);
        } 
        
        if ((soma == 2) || (soma == 3) || (soma == 12)){
            JOptionPane.showMessageDialog(this, "Você perdeu!", "Tente mais uma vez", JOptionPane.INFORMATION_MESSAGE);
            
            // obtendo a string do saldo
            //int saldo = new Integer(jLSaldo.getText());
            
            // obtendo a sting da aposta
            int aposta = new Integer(jTFAposta.getText());
            
            // diminuindo o jLSaldo
            saldo -= aposta;
            
            // gravando no jLSaldo
            jLSaldo.setText(""+ saldo);
        }
        
        // Coloque aqui toda lógica do seu jogo (perdeu, ativar/desativar, botoes)
        if (saldo <= 0) {
            JOptionPane.showMessageDialog(this, "Você perdeu!", "Está sem sorte!", JOptionPane.INFORMATION_MESSAGE);
            
            /* Ativando e desativando componentes na tela */
            jBLancar.setEnabled(false);
            jBApostar.setEnabled(false);
            jTFAposta.setEnabled(false);
            
            System.exit(0);
        }
    }

    /**
     * Após lançar os dados, deve-se verificar a soma e fazer todo o cálculo do
     * jogo.
     *
     * Este método está incompleto e precisa ser corrigido.
     *
     * @param evt
     */
    private void jBLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLancarActionPerformed

        /* Sempre que pressionar o botão LANÇAR DADOS, o número máximo
         * de saltos para cada dado será escolhido de forma aleatoria */
        int limiteDeSaltoDado1 = r1.nextInt(50) + 10;
        int limiteDeSaltoDado2 = r1.nextInt(50) + 10;

        Dado dado1 = new Dado("dado1", this.jLDado1, limiteDeSaltoDado1);
        Dado dado2 = new Dado("dado2", this.jLDado2, limiteDeSaltoDado2);
        
        Controle n = new Controle(dado1, dado2, this);
        
        n.start();

        /* lançando os dados, a simulação com troca das faces do dado
        deverá ser mostrada na interface com o usuário */
//        dado1.start();
//        dado2.start();
       

        /*
         Cada dado saltará um número aleatório de vezes, então pode ser que um
         termine de saltar antes do outro. É importante obter o valor e fazer
        a soma das faces somente após ambos pararem de saltar.
        
        Ou seja, a lógica apresentada nas linhas abaixos está errada, 
        pois 3 threads estão concorrendo.
         */
        
//        this.faceDado1 = dado1.getValorSorteado();
//        System.out.println("Principal: dado1: " + this.faceDado1);
//        this.faceDado2 = dado2.getValorSorteado();
//        System.out.println("Principal: dado2: " + this.faceDado2);
//        
//        //System.out.println("valor pra teste" + dado1.getValorSorteado());
//        verificaSoma();
        
    }//GEN-LAST:event_jBLancarActionPerformed

   
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
            
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBApostar;
    private javax.swing.JButton jBLancar;
    private javax.swing.JLabel jLBuscado;
    private javax.swing.JLabel jLDado1;
    private javax.swing.JLabel jLDado2;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLTotalLancamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTFAposta;
    // End of variables declaration//GEN-END:variables
}
